export const FETCH_USER = 'FETCH_USER';
export const FLOORS_AMOUNT = 'FLOORS_AMOUNT';

export const RADIO_BUTTON_FLOORS = 'RADIO_BUTTON_FLOORS';
export const RADIO_BUTTON_APPARTMENTS = 'RADIO_BUTTON_APPARTMENTS';
